### ISSUE TITLE
[BUG]: Jupyterlab strange tab-autocomplete fails for instantiated classes within cells

### ISSUE THREAD

**Issue by pmreyes2** [EarthCubeInGeo/resen-core#53] opened 2020-06-27 05:59 UTC
Tested both in resen-core 2019.1.0 and 2020.1.0 the issue happens only in their notebooks with py36 kernels.
GIF illustrating the issue:

![py36_notebook_autocompletion](https://user-images.githubusercontent.com/3052100/85915921-7aebb580-b800-11ea-86e4-2ce77fb814f0.gif)

Autocomplete with tab fails in the second line, after `a=np.arange(10)` in the second cell. In a new cell it works fine, also if used in the first line of cell 2, before `a=np.arange(10)`. Surprisingly it also works when removing the right parenthesis of `np.arange` or erasing the a to the left of `np.arange`.

A similar issue was reported in the Jupyter notebook github repository: [https://github.com/jupyter/notebook/issues/4305](https://github.com/jupyter/notebook/issues/4305). Will check later if that solution helps.

**Comment by pmreyes2** [comment] 2020-06-29 16:51
Testing the solution offered at the end of the thread: [https://github.com/jupyter/notebook/issues/4305](https://github.com/jupyter/notebook/issues/4305) , which is to disable [jedi autocompletion](https://jedi.readthedocs.io) and use the default:

- `(py36) jovyan@2f775514dfed:~$ ipython profile create default`
- edit ~/.ipython/profile_default/ipython_config.py
and add: `c.IPCompleter.use_jedi = False`

Now normal behavior of autocompletion for py36 ipython and notebooks is restored, but the nice [jedi autocompletion](https://jedi.readthedocs.io) is disabled.:

GIF illustrating the new behavior (jedi autocompletion disabled):

![py36_ipython_nojedi](https://user-images.githubusercontent.com/3052100/86033457-cfa05380-b9ed-11ea-8b1e-1c07df363d95.gif)

This other open thread report the same issue of `ipython`: [https://github.com/ipython/ipython/issues/11530](https://github.com/ipython/ipython/issues/11530)

**Comment by asreimer** [comment] 2020-08-06 21:52
So this is a problem with the jupyterlab interface. We should track what they do to fix the problem and make sure we upgrade to the next release with the bugfix.

**Comment by asreimer** [comment] 2020-09-10 01:06
Revisiting this again it was a feature of the jedi package for security reasons, but as of jedi 0.15.0, the issue is fixed.
See: https://github.com/ipython/ipython/issues/11546#issuecomment-520253924 For the discussion on safety, see here: https://github.com/davidhalter/jedi/issues/1299#issuecomment-475369943

So, I created a new 2020.1.0 bucket and tried the autocomplete example that @pmreyes2 mentioned. We're currently running jedi 0.17.0 in the py36 environment and I can reproduce the problem. If I upgrade jedi to 0.17.2, the issue goes away.

Can you confirm this @pmreyes2?

**Comment by pmreyes2** [comment] 2020-09-10 01:30
@asreimer, that's great. Yes, by upgrading jedi to 0.17.2, the issue goes away.

**Comment by asreimer** [comment] 2020-09-10 02:15
Added jedi 0.17.2 to #59. Closing issue.

**Closed as completed by asreimer** 2020-09-10 02:15 UTC
Labels: bug
