### ISSUE TITLE
Outdated OMNI data in spacepy

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen-core#36] opened 2019-10-18 23:37 UTC
Our installation of spacepy currently only includes OMNI data up to January 31, 2017.  Given that this is over a year and a half ago at this point, this is somewhat inconvenient.  According to the [spacepy documentation](https://pythonhosted.org/SpacePy/autosummary/spacepy.toolbox.update.html#spacepy.toolbox.update), you should be able to update the database by executing the following:
```
>>> import spacepy.toolbox as tb
>>> tb.update(omni=True)
```
However, every time I've tried this, the process is killed, which causes the Kernel to restart.

**Comment by ljlamarche** [comment] 2019-10-23 19:06
At least part of this is actually a spacepy issue related to where it's pulling OMNI data from (spacepy/spacepy#233).  That doesn't explain why the process is sometimes killed, but that might be related to how processes and resources allocation are handled between the host machine and container.

**Comment by asreimer** [comment] 2019-10-24 21:14
I cannot reproduce the "process getting killed" error you are seeing. As we discussed in the meeting today, this might have been caused by other things you were doing at the same time (running a model, etc).

**Comment by asreimer** [comment] 2019-10-24 21:14
Seems like we'll have to wait for spacepy to fix this, so I'm closing this issue.

**Closed as completed by asreimer** 2019-10-24 21:14 UTC
Labels: wontfix

**Comment by jtniehof** [comment] 2020-01-02 17:45
spacepy master now pulls the OMNI2 data from SPDF; don't know which database you're using but that might help. Also spacepy docs are now at https://spacepy.github.io/ ; I pushed the delete button on the pythonhosted ones but they aren't actually deleted, and Google still puts that result higher (unfortunately).

**Comment by asreimer** [comment] 2020-01-02 18:20
Thanks @jtniehof!

It will take a couple days or weeks for Google to change the results as the re-cache everything.
